#ifndef CONFIG_H
#define CONFIG_H

/* SENSOR */
#define SENSOR_COUNT 5
#define SENSOR_ACTIVE_BLACK 0

/* MOTOR */
#define PWM_MAX 999
#define PWM_MIN_RUN 180
#define LEFT_PWM_BIAS 20
#define RIGHT_PWM_BIAS 22
#define LEFT_MOTOR_INVERT 0
#define RIGHT_MOTOR_INVERT 1

#define BASE_SPEED 95.0f
#define MAX_SPEED 100.0f
#define SEARCH_FORWARD_SPEED 90.0f
#define SEARCH_REVERSE_SPEED 20.0f

/* CONTROL */
#define CONTROL_INTERVAL_MS 3U
#define DEBUG_INTERVAL_MS 500U
#define REPORT_INTERVAL_MS 1000U
#define START_DELAY_MS 1000U
#define LINE_CENTER_POS 2000.0f
#define KP 34.0f
#define KD 32.0f
#define MAX_CORRECTION 60.0f
#define MIN_AUTO_SPEED 36.0f

#define STOP_ON_ALL_BLACK 1
#define ALL_BLACK_CONFIRM_CYCLES 40U

/* MANUAL */
#define MANUAL_FWD_RELEASE_TIMEOUT_MS 250U
#define MANUAL_BWD_RELEASE_TIMEOUT_MS 500U
#define MANUAL_TURN_RELEASE_TIMEOUT_MS 120U

#endif
